# Generated by Django 3.0.2 on 2020-03-22 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromodemModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='В архиве?')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('ip', models.GenericIPAddressField()),
                ('brightness', models.IntegerField(verbose_name=' Яркость светильника ')),
                ('wifi_signal', models.IntegerField(verbose_name=' Уровень принимаемого сигнала WiFi ')),
                ('project_code', models.IntegerField(verbose_name=' Код проекта ')),
                ('modification_code', models.IntegerField(verbose_name=' Код модификации ')),
                ('voltage_inversion', models.BooleanField(verbose_name=' Инверсия напряжения ')),
                ('threshold_brightness_level', models.IntegerField(verbose_name='Пороговый уровень яркости для автоматического срабатывания реле ')),
                ('register_values', models.CharField(max_length=2, verbose_name=' Значения однобитовых регистров ')),
                ('brightness_value_when_turned_on', models.IntegerField(verbose_name='Уровень Яркости 0…100% при включении ')),
                ('brightness_step', models.IntegerField(verbose_name=' Шаг изменения яркости ')),
                ('minutes_to_brightness_reset', models.IntegerField(verbose_name='Количество минут до сброса яркости на дефолт')),
                ('brightness_after_reset', models.IntegerField(verbose_name='Дефолтная яркость')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Промодем ',
                'verbose_name_plural': 'Промодемы ',
            },
        ),
    ]
